### ISSUE TITLE
Source tree references "displays" several places, but this is not a display library

### ISSUE THREAD

**Issue by hachi** [adafruit/Adafruit-PWM-Servo-Driver-Library#14]
README.md, and all of the source files state "These displays use I2C to communicate, 2 pins are required to interface."

I think this was just copied and pasted from some other source tree, because this is not even for a display.

**Comment by DamienMiras** [comment]
mya be not because the adafruit board could be used to drive led monochrome or 4x4 led display matrix ;)

**Comment by ladyada** [comment]
fixed in latest commit
