### ISSUE TITLE
Is it possible to use output not as PWM but as normal Digital Output?

### ISSUE THREAD

**Issue by nkint** [adafruit/Adafruit-PWM-Servo-Driver-Library#15]
Such as a multiplexer, in other word. To switch on/off mechanical relay and use simultaneously: for example 4 relays and 12 pwm.
Is it possible? Is there any example code?

**Comment by DamienMiras** [comment]
I don't think so because the component soldered in the adafruit board is not a multiplexer it is intend to output pwm signal see the datasheet here https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf

**Comment by ladyada** [comment]
a gpio test example has been added!
