### ISSUE TITLE
No output if PWM freq not set

### ISSUE THREAD

**Issue by conorpeterson** [adafruit/Adafruit-PWM-Servo-Driver-Library#18]
The setPWM function doesn't work unless users first call setPWMFreq. So while example sketches work, if users attempt to use the library with the PWM frequency left at default nothing will work.

It could probably be fixed by setting the Auto-Increment bit of the MODE1 register in begin(), perhaps right after that call to reset().

**Comment by ladyada** [comment]
changed so begin() will set a 1khz frequency default
