### ISSUE TITLE
The library does not work with Arduino Due

### ISSUE THREAD

**Issue by Hamulus** [adafruit/Adafruit-PWM-Servo-Driver-Library#22]
This library works great with Mega and does not work with Due. It seems like because of some issues in arduino core Wire library.

**Comment by ladyada** [comment]
Tested and it definitely...works. just not well :(

**Comment by btickell** [comment]
Is this still an issue? I am trying to run the servo test script and am using identical connections as I have successfully tested with an Uno.

**Comment by Hamulus** [comment]
I have not tried new version (the last date when I tested was Sep 9 2016:) ) because I found completely other solution without PCA9685.
However please note, that Due has completely different chip than Uno. In my initial post I mentioned that the library worked perfect with Mega, so Mega and Uno are more similar than Due and Uno or Due and Mega. So if you really want to check, you should use exactly Due, not Uno or Mega.
