### ISSUE TITLE
enable disable PWM

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [adafruit/Adafruit-PWM-Servo-Driver-Library#35]
Would be great to have the ability to sleep/wakeup the board.
I had some strange issues with Servo motors. In some interval they slightly changed the position or vibrates in some positions.

For my case it is not needed to hold one value - I just drive the servo to one position and want to pause it (so no pwm/power is send)

Just add these little helper methods to send the board to sleep and wakeup again.
Maybe these methods would be great to have inside the lib:

```
void sleepServo() {
  uint8_t awake = read8(PCA9685_MODE1);
  uint8_t sleep = awake | 0x10; // set sleep bit high
  write8(PCA9685_MODE1, sleep);
  delay(5); // wait until cycle ends for sleep to be active
}

void wakeupServo() {
  uint8_t sleep = read8(PCA9685_MODE1);
  uint8_t wakeup = sleep & ~0x10; // set sleep bit low
  write8(PCA9685_MODE1, wakeup);
}
```

**Comment by hoffmannjan** [comment]
added in #46. thanks! 👍
