### ISSUE TITLE
AS/Atmega library or examples?

### ISSUE THREAD

**Issue by johnyradio** [adafruit/Adafruit-PWM-Servo-Driver-Library#36]
The examples appear to be Arduino only. I tried porting to Atmel Studio for Atmega 328P and got a "recipe" error. 

Any working examples for Atmel Studio?

**Comment by johnyradio** [comment]
Also, the examples and/or library appear to be written for order versions of Wire and/or TinyWire. Getting error mentioned in another issue. 

Any up-to-date examples available?

**Comment by johnyradio** [comment]
*older

**Comment by ladyada** [comment]
hiya this code is offered 'as-is' for arduino. but its not that complex, it could be ported to any platform (but we don't have support for that)
