### ISSUE TITLE
Serial Communication Adafruit_PWMServoDriver

### ISSUE THREAD

**Issue by TheVeryDesperateStudents** [adafruit/Adafruit-PWM-Servo-Driver-Library#39]
For our project we are using the adafruitPWMservodriver library. We are using the Arduino Mega 2560 in combination of the servoshield 16 x12 bits PWM. We want to use serial communication to send the motor positions to the servo. We want to send the commands using MATLAB/ Simulink. The command we send is :UU123456 (UU followed by 6 motor positions). We are sending the data as uint8. The code we are using to read the data is, but this shouldn't have any problems: 
void serialEvent() {

  if (Serial.available()>0) {
    
    digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
    // get the new byte array:
    char inChar = Serial.readBytes(readStream, 8);
  }
}

We think the fault lies in the way we are sending the data. Does anyone have any advice or insight?

**Comment by ladyada** [comment]
hiya this isn't an issue or question about the library
