### ISSUE TITLE
i2c pin

### ISSUE THREAD

**Issue by ramarro123** [adafruit/Adafruit-PWM-Servo-Driver-Library#42]
hi,

can i suggest to add i2c pins to begin constructor? in that way, non standard controller are able to use the library without need to modify it.

some esp8266 are limited and have to reuse pins for i2c, so using Wire.begin(x,y) can be quite useful.

**Comment by ladyada** [comment]
hiya you can pass in any Wire device you like here
https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/blob/master/Adafruit_PWMServoDriver.cpp#L48
