### ISSUE TITLE
Compiling for ATtiny85

### ISSUE THREAD

**Issue by rirod17** [adafruit/Adafruit-PWM-Servo-Driver-Library#44]
Hello.

I'm trying to connect a Adafruit 16-Channel 12-bit PWM/Servo Driver - I2C interface - PCA9685 to Adafruit Trinket 5V (ATtiny85 @ 8MHz) through I2C. Currently using Arduino 1.8.5 (Mac OS X).

The Trinket doesn't allow Serial with the standard "Wire.h" Arduino library. I saw, with the same error as me, this post: 
https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/issues/34
And I tried with the specific "Wire" library:
https://github.com/adafruit/Adafruit_Arduino_Boards/tree/master/libraries/Wire
But still no success. I'm pretty positive the compiler is loading the correct library, since it's the one set under Doc/Arduino/libraries.

Any work around you can think of?

**Comment by ladyada** [comment]
hiya closing cause we dont have a solution other than purchasing a Trinket M0 which has lots of memory and peripherals!
