### ISSUE TITLE
cannot find wiring diagram

### ISSUE THREAD

**Issue by javirs85** [adafruit/Adafruit-PWM-Servo-Driver-Library#48]
Hi, where can people find a wiring diagram? In the comments it says one needs two pins but .. what are the default pins?

Thanks in advance

Note: I´m using it with a nodeMCU Lolin board

**Comment by Bolukan** [comment]
It seems I2C to me. So D5/gpio14 for CLK and D4/gpio2 for SDA as default I2C pins.
