### ISSUE TITLE
Method for setting push pull/open drain mode

### ISSUE THREAD

**Issue by tbolin** [adafruit/Adafruit-PWM-Servo-Driver-Library#54]
The board is advertised as supporting both open drain and push-pull configurations for the output pins. The library currently does not expose this functionality.

I suggest that a setOutputMode method is added that can change the mode. 

- Arduino board:  Any

- Arduino IDE version (found in Arduino -> About Arduino menu):  Any

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): NA

**Comment by ladyada** [comment]
thanks - please submit a PR and we'll take a look!

**Comment by tbolin** [comment]
Pull request submitted

**Comment by tbolin** [comment]
Pull request merged so I'm closing the issue.
