### ISSUE TITLE
Program may freeze if hardware fails.

### ISSUE THREAD

**Issue by bask185** [adafruit/Adafruit-PWM-Servo-Driver-Library#82]
Working with the PCA9685 often gave me a software crashing problem. The cause was faulty wiring, but the real problem is that the functions of this library do no seem to return when that is the case. This causes any program to hang. If I would touch the wires, suddenly the program would go on.

**Comment by PePeLLee** [comment]
Did someone find any good alternative library that covers this issue?

**Comment by bask185** [comment]
The problem lies not in this library but in the Wire library of Arduino.
